site_name: Gufo Labs Loader
site_description: Gufo Labs Loader Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_loader/"
copyright: "&copy; 2022, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_loader/
repo_name: GitHub
nav:
  - Home: index.md
  - Installation: installation.md
  - Reference: reference.md
  - Examples:
      - Overview: examples/index.md
      - Subclass Scheme: examples/subclass.md
      - Protocol Scheme: examples/protocol.md
      - Singleton Scheme: examples/singleton.md
  # Contributing: contributing.md
  - FAQ: faq.md
  - Changes: changes.md
  - License: license.md
  # Users
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - src/gufo/
        - examples/
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
