site_name: Gufo Labs Loader
copyright: "&copy; 2022, Gufo Labs"
site_dir: dist/docs/
nav:
  - Home: index.md
  - Installation: installation.md
  - Reference: reference.md
  - Examples:
      - Overview: examples/index.md
      - Subclass Scheme: examples/subclass.md
      - Protocol Scheme: examples/protocol.md
      - Singleton Scheme: examples/singleton.md
  #  Contributing: contributing.md
  # - FAQ: faq.md
  - Changes: changes.md
  - License: license.md
  # Users
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      watch:
        - src/gufo_loader
        - examples/
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
