site_name: Gufo Loader
site_description: Gufo Loader Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_loader/"
copyright: "&copy; 2022, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_loader/
repo_name: GitHub
nav:
  - Home: index.md
  - Installation: installation.md
  - Reference: reference.md
  - Examples:
      - Overview: examples/index.md
      - Subclass Scheme: examples/subclass.md
      - Protocol Scheme: examples/protocol.md
      - Singleton Scheme: examples/singleton.md
  - Developers' Guide:
      - Developer's Environment: environment.md
      - Building and Testing: testing.md
      - Common Tasks: devcommon.md
      - Code Quality: codequality.md
      - Code Base: codebase.md
      - Contributing Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
  - Supported Standards: standards.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: license.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
watch:
  - docs/
  - src/gufo/
  - examples/
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
